name: LaTeX to PDF

on:
  push:
    tags: v*.*.*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Build docker image
        uses: kumatheworld/textbook-solutions/.github/actions/latex@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
